# Generated by Django 5.1.5 on 2025-01-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
