# Generated by Django 5.1.5 on 2025-03-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companysite', '0003_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='image',
            field=models.ImageField(upload_to='creation/'),
        ),
    ]
